### ISSUE TITLE
/aqo restart command causes mq2lua crash

### ISSUE THREAD

**Issue by towbes** [aquietone/aqobot#1]
Getting a crash in mq2lua.dll when using /aqo restart.  Clicking Restart from the UI works fine.

Also works fine to manually run the lua from console '/multiline ; /lua stop aqo ; /timed 5 /lua run aqo'

Steps to reproduce:
1. /lua run aqo
2. /aqo restart

This is with Red Guides latest version from 1/28/2024 6:15:10 AM (based on red guides launcher)

Not sure what other information might be relevant...

Other Luas running:
buttonmaster
binds/formations
lem
boxhud

**Comment by towbes** [comment]
Stepped through the command, no crash happens when restart is set to only mq.cmd('/multiline ; /lua stop aqo')

The crash seems to happen right away after adding the "/timed 5 /lua run aqo".  Increasing the timed value doesn't seem to change the behavior, still crashes right when running /aqo restart command

**Comment by aquietone** [comment]
should work now, moved the stop into main loop instead of the bind. seems like a bug in mq2lua
