### ISSUE TITLE
Changing Pull radius does not clear pull list

### ISSUE THREAD

**Issue by towbes** [aquietone/aqobot#10]
Steps to reproduce (This was with magician using pullwith custom option)

1. Set pull radius to 1000 and set to puller tank mode, char will start pathing to the mob, turn to manual mode
2. Set pull radius to 200 and set to puller tank mode, char will start pathing towards the same previous mob if there are no other mobs in the radius

**Comment by aquietone** [comment]
should reset pull state on any pull setting change now
