### ISSUE TITLE
Trouble with Bard Custom Rotation

### ISSUE THREAD

**Issue by towbes** [aquietone/aqobot#11]
Bard is not doing a song rotation when set to 'custom' mode. They do still use brusco's bellow on the pull, but don't sing any buff songs

![image](https://github.com/aquietone/aqobot/assets/7587673/6a947871-27f4-4301-a7ee-81f899898da0)

Spell Gems:
![image](https://github.com/aquietone/aqobot/assets/7587673/d589e681-0679-4ed0-b1f3-faee2e6e5d31)

from the config lua file:
```
	['BYOSCustom'] = {
		[1] = 'warmarch',
		[2] = 'spiteful',
		[3] = 'pulse',
	},
	```

**Comment by aquietone** [comment]
this byos custom was a pretty recent / not too fleshed out addition. i think right now it only really works for caster dps spell rotations, doesn't work for heals or buffs or bards etc for example. will need to look into making the bard take advantage of it, not ideal but you can also enable usetwist and aqo won't try to play any songs, so you can just use mq2twist alongside it.

**Comment by aquietone** [comment]
Updated bard to make use of this custom spell rotation now.
If BYOS == true and custom spell rotation length > 0 and spellset is set to custom, it will cast the songs in the order they are defined in the custom rotation.
You're on your own for mem'ing the songs to match the rotation defined.

**Comment by aquietone** [comment]
Note that mez songs aren't included as options in the custom rotation, and it will still try to mez based on the mez options that are enabled. It also won't use the selos song if you don't include it in the rotation. Added a new option so that selos AA can be toggled to be used in case you don't want to add the song to the rotation.

**Comment by towbes** [comment]
I think we don't have selo's AA on our server.  I'm not seeing Selo's Accelerating Chrous as an option in custom:

![image](https://github.com/aquietone/aqobot/assets/7587673/3f133df0-59e9-4323-81ab-92af7651eaf9)

It's showing in spell abilities:
![image](https://github.com/aquietone/aqobot/assets/7587673/9b495729-954c-48cc-ad62-b97940cfd1ee)

**Comment by towbes** [comment]
Fixed it by adding selos into the dps group:
```
Bard.allDPSSpellGroups = {'aria', 'arcane', 'chantfrost', 'spiteful', 'firenukebuff', 'chantflame', 'suffering', 'insult', 'warmarch', 'sonata', 'firemagicdotbuff', 'chantdisease',
    'crescendo', 'pulse', 'composite', 'dirge', 'insultpushback', 'chantpoison', 'alliance', 'overhaste', 'bardhaste', 'emuhaste', 'snare', 'debuff', 'jonthans', 'magicweapons',
    'chantmagic', 'aedot', 'aeslow', 'manasong', 'dispel', 'selos'}
```
