### ISSUE TITLE
Bard doesn't finishing casating Aura of Insight

### ISSUE THREAD

**Issue by towbes** [aquietone/aqobot#15]
Spellset: emuaura65 

Bard is 65 at PoP expansion

They mem Aura of Insight, click it, but immediately stop casting and re-mem mez song into that slot.  It gets the bard stuck in a loop as they later will sit down to try to activate the Aura of Insight, but never actually finish casting it.  I have to manually pause, cast aura of insight, then unpause and seems to work as expected from there (does not try to recast the aura)

Settings picture:
![image](https://github.com/aquietone/aqobot/assets/7587673/f3797a3f-1930-4cd2-8934-5cc46cdcd1d8)

**Comment by aquietone** [comment]
Having trouble reproducing this one too. Can you screenshot the spell info from view abilities window? And also there is no aura in the aura window shift+A?

**Comment by towbes** [comment]
Here is the spell
![image](https://github.com/aquietone/aqobot/assets/7587673/6aa4b63f-8a92-4021-b530-e46e6c977765)

It seems like she's trying to use it but then jumps to a song before finishing cast
![image](https://github.com/aquietone/aqobot/assets/7587673/4c28f96c-e0df-4dea-bee8-ed16ab3ba00e)

She doesn't have the aura active
![image](https://github.com/aquietone/aqobot/assets/7587673/1c34ae0a-a5ae-491a-9161-15de77fd28ff)

**Comment by towbes** [comment]
Should the bard aura qualify as a spell not an ability? Seems to cast the same way a song does.  However it's getting called with ability.use instead of the spell:cast() that is used in the findnextsong part in brd.lua

**Comment by aquietone** [comment]
ability.lua has a few too many ways to do things.
ability.use takes in any type of spell, aa, disc, item, skill

It might be because of the 6 second cast time. Since generally every bard song on live and lazarus at least are all fixed 3 second casts, i think the bard codes not expecting something to take longer.

**Comment by aquietone** [comment]
pushed a maybe workaround for it, guess we'll see

**Comment by towbes** [comment]
Bard is casating aura of insight as expected with that fix!
