### ISSUE TITLE
When using Manual target mode, cannot turn of Switch with MA

### ISSUE THREAD

**Issue by towbes** [aquietone/aqobot#16]
The melee DPS never gets this line in the debug log:

            logger.debug(logger.flags.routines.assist, "checkTarget not switching targets with MA, staying on "..(mq.TLO.Target.CleanName() or ''))

I tried moving around the check but it broke the targeting in unexpected ways. 

Is there a way to make it so melee wont' switch with the MA when manual assist mode is used? (Which I think is a requirement on EMU?)

**Comment by aquietone** [comment]
The problem with manual assist mode is it just relies on issuing manual /assist commands on a timer. This mode was added for a couple reasons:
- Group MainAssist on EMU doesn't seem to work while in raids
- Raid MainAssist on EMU doesn't seem to work at all
- I raid with friends and we want one tank to be able to MA, so need something that didn't rely on dannet/local PC

Should be able to make manual assist honor switch with MA and just not call /assist if already assisting and switch with MA is false. But this will also mean that the logic to backoff when MA targets themself won't work in manual assist mode if switch with MA is false.

**Comment by aquietone** [comment]
Pushed that change, so if you want the backoff from MA targeting themself, then switch with MA needs to be on.

**Comment by towbes** [comment]
This is working awesome thank you
