### ISSUE TITLE
Rogue aggroClass() too short delay to trigger aggro reducer

### ISSUE THREAD

**Issue by towbes** [aquietone/aqobot#18]
Rogues should get a message in chat "You have momentarily ducked away from the main combat" when they successfully drop aggro with hide.  I think the delay between autoattack off and hide was not long enough on the server i'm playing on so i forced it to a 1000 delay and consistently get the message now

```
function Rogue:aggroClass()
    if mq.TLO.Me.AbilityReady('hide') then
        if mq.TLO.Me.Combat() then
            mq.cmd('/attack off')
            --mq.delay(1000, function() return not mq.TLO.Me.Combat() end)
            mq.delay(1000)
        end
        mq.cmd('/doability hide')
        mq.delay(500, function() return mq.TLO.Me.Invis() end)
        mq.cmd('/attack on')
    end
end
```

**Comment by towbes** [comment]
While troubleshooting this issue I also saw in classbase.lua the aggro functions are only triggered on named mobs, is that intended?

[classbase.lua line 880:](https://github.com/aquietone/aqobot/blob/508912d3af6d4f5cf6b9e8c4d59c743914598d17/classes/classbase.lua#L843)

if mq.TLO.Target() and pctAggro >= 70 and mq.TLO.Target.Named() then

**Comment by aquietone** [comment]
Updated to fixed delay and removed the named check
