### ISSUE TITLE
Move buff beg lists out of Constants.lua

### ISSUE THREAD

**Issue by aquietone** [aquietone/aqobot#19]
Lists of what classes want what buffs was initially defined in Constants.lua just to get going and test out mostly static actor based buff begging.
Ideally it should be configurable per class in some way / more dynamic / overridden by user. Particularly with decisions around temp vs skin+symbol type lines or SV vs brells vs predator.

**Comment by aquietone** [comment]
The Skills tab has a new `Buffs` button, which opens a window for configuring buffs to offer and buffs to beg for.
The buff begging system in AQO uses the actor system, so is limited to local PC characters.
Characters who have buffs available to offer can enable those buffs under the `Offer Buffs` section of the buffs window. This will cause those enabled buffs to be broadcast to other characters.
Characters who want buffs can enable what buffs they want in the `Want Buffs` section of the buffs window. This will cause those characters to broadcast what buffs they want to other characters. They will only ask for buffs which are being broadcast as available.

The offered / requested buffs can be seen by expanding `actors` in the state inspector from debug tab.

This can also be configured via CLI:
- /aqo buffaliases -- this command lists all available buff aliases which can be configured
- /aqo wantbuff aego on -- this command would turn on begging for aego buff line
- /aqo offerbuff aego on -- this command would turn on offering aego buff line

**Comment by aquietone** [comment]
![image](https://github.com/aquietone/aqobot/assets/100880604/3939e492-03a7-451d-9586-5f974b80fd70)

![image](https://github.com/aquietone/aqobot/assets/100880604/74f19461-81dd-4f04-afea-fbb22ea12257)

**Comment by towbes** [comment]
This is awesome!  Just for the history books...we chatted in DM about some issues where when chars are logged in across multiple servers it can cause some weird behavior for advertising/asking for buffs

**Comment by towbes** [comment]
As you mentioned, adding this to the send header in status.lua seems to have solved the cross server issue
```
local header = {script = 'aqo', server = mq.TLO.EverQuest.Server()}
```

**Comment by aquietone** [comment]
added server to the header
