### ISSUE TITLE
Feature Request: Command for saving char settings

### ISSUE THREAD

**Issue by towbes** [aquietone/aqobot#2]
Adding this as an issue for now just to not forget about it. For changes that are minor like this, is it better to just submit directly as a merge request?

The reason for the change would be for multiboxing situations to avoid having to click every UI window.  Some future state might be the potential to save with different suffix filename to allow for different profiles for different fights. (with a corresponding load command that might load specific char/class settings based on a suffix)

Update to commands.lua in function commands.commandHandler(...)

    elseif opt == 'SAVE' then
        class:saveSettings()

Should there be some indication in console that the settings were saved?

**Comment by aquietone** [comment]
`/aqo save` or `/classname save` should work now
