### ISSUE TITLE
Debuff Priority

### ISSUE THREAD

**Issue by towbes** [aquietone/aqobot#21]
How is the debuff priority decided? From what I can tell it's just cycling through the spells where debuff=true in the class file.  As an example these spells get loaded as debuff on my shaman:

![image](https://github.com/aquietone/aqobot/assets/7587673/8231a4c9-deaf-406c-9f8e-9fdb3efeb29c)

It looks like it's ending up alphabetical, and then casting in that order.   Is there a way to make malo -> slow the priority?

**Comment by aquietone** [comment]
the alpha order looks like i just got lucky and wrote the spells out in that order in the big table of spells.
if you look in debuff.lua, castDebuffs has a order it looks for available debuff spells:
- dispel
- debuff aoe
- debuff
- slow aoe
- slow
- snare

**Comment by towbes** [comment]
Ok, this is something that I would update myself in debuff.lua for specific fights/classes.  Is there any override possible in a class.lua file?

**Comment by aquietone** [comment]
![image](https://github.com/aquietone/aqobot/assets/100880604/d4fc9ae6-fa91-40e2-84e9-2039f4abd982)

its ugly but you can drag/drop reorder them by type at least. each also corresponds to an option each class with debuffs should have like USESLOW, USESLOWAOE, USEDEBUFF, USEDEBUFFAOE, USESNARE, DISPEL

**Comment by towbes** [comment]
Nice this is perfect ty
