### ISSUE TITLE
Camping Healers out of LOS

### ISSUE THREAD

**Issue by towbes** [aquietone/aqobot#22]
When doing a boss fight where I positioned with healers out of LOS to avoid AoEs, I noticed that they immediately put themselves in LOS before casting heals.

I think this is part of the doAssist routine, when i commented out the assist.checkLOS() they would heal without moving into LOS.  What would be the best way to avoid having a cleric hit that?  Maybe just set their assist min to 101?
```
function assist.doAssist(reset_timers, returnAfterAnnounce)
    local assistMobID = assist.getAssistSpawnIncludeManual()
    if assistMobID == 0 then return false end
    if assist.checkMATargetSwitch(assistMobID) then
        if assist.targetAssistSpawn(assistMobID) then
            assist.setAndAnnounceNewAssistTarget(assistMobID, reset_timers)
            if returnAfterAnnounce then return true end
        end
    end
    if state.assistMobID == 0 then return false end
    if not state.medding or not config.get('MEDCOMBAT') then
        if class:isAbilityEnabled('USEMELEE') then
            assist.getCombatPosition()
            if state.assistMobID and state.assistMobID > 0 and not mq.TLO.Me.Combat() and class.beforeEngage then
                logger.debug(logger.flags.routines.assist, "beforeengage")
                class:beforeEngage()
            end
            assist.engage()
        else
            --assist.checkLOS()
        end
    end
    assist.sendPet()
    return true
end

```

**Comment by aquietone** [comment]
might be easiest to just put them into manual mode? or you could cheat and do a /rootme
they try to get los because even healers still tend to have some debuff or nuke or something in their lineup somewhere.

**Comment by towbes** [comment]
Ah ok Manual mode should work, didn't realize that would let them keep healing.  Will give that a go next time thanks
