### ISSUE TITLE
Bard Song High Latency Issues

### ISSUE THREAD

**Issue by towbes** [aquietone/aqobot#23]
I noticed that my bard was repeating song casts a lot.  I play from Japan -> US server so my ping is probably pretty high.  I adjusted the delays in doneSinging() and it prevented the double casts from happening.  Not sure if this is something worth accounting for in a setting somewhere but wanted to throw it out there in case others see it happening
```
function Bard:doneSinging()
    if self:isEnabled('USETWIST') then return true end
    if mq.TLO.Me.CastTimeLeft() > 0 and not mq.TLO.Window('CastingWindow').Open() then
        mq.delay(750)
        mq.cmd('/stopsong')
        mq.delay(100)
    end
    if not mq.TLO.Me.Casting() then
        if self:isEnabled('USESELOSAA') and self.selos and selosTimer:expired() then
            self.selos:use()
            selosTimer:reset()
        end
        return true
    end
    return false
end
```

**Comment by aquietone** [comment]
debug tab or /aqo delayforlag number
i only added it in your one spot mentioned above but it could be used anywhere its needed.
`mq.delay(250+config.get('DELAYFORLAG'))`

**Comment by towbes** [comment]
This is working awesome thanks
