### ISSUE TITLE
buff.lua logger crash

### ISSUE THREAD

**Issue by towbes** [aquietone/aqobot#27]
Was troubleshooting some buffing and uncommented a logger statement but it caused a crash.
![image](https://github.com/aquietone/aqobot/assets/7587673/d190110c-dc9a-49e6-9146-1591ea124eb5)

In buff.lua [#156](https://github.com/aquietone/aqobot/blob/emu/routines/buff.lua#L164)

**Comment by aquietone** [comment]
tried uncommenting this log and it seemed fine, not sure what happened there.

**Comment by towbes** [comment]
Hmm maybe was a buff I added to a class somewhere..will check with a fresh pull and add my class files one by one. Afk for a couple weeks so will try this mid may
