### ISSUE TITLE
Multiple Berserker and Aura of Rage

### ISSUE THREAD

**Issue by Kausaliax** [aquietone/aqobot#30]
Ok so I'm aaing some berserkers in the same group.  They all are trying to cast Aura of Rage.  The issue is they get the spam however they get 'You do not have sufficient focus to maintain that ability'.  
In spamming that they run themselves out of end.  While they try to cast it they are also not engaging the mob.

I have one aa'd berserker out of group and don't have this issue at all.

Do you see any way to address this?  Maybe a toggle to disable combat skills so there is no conflict and waste of dps?

**Comment by aquietone** [comment]
what's the name of the aura in the song window?

**Comment by Kausaliax** [comment]
Aura of Rage Effect

**Comment by aquietone** [comment]
tried adding a check for if its already in song window, in case some other ber already has aura up. can see whether that fixes it for you

**Comment by Kausaliax** [comment]
Will test it out.

**Comment by Kausaliax** [comment]
That's working.  Thank you )
