### ISSUE TITLE
Buff issues

### ISSUE THREAD

**Issue by Kausaliax** [aquietone/aqobot#31]
I noticed druids do not give damage shield buffs or wrath of the wild aa damage shield buff.

Paladins do not have any offer buffs.  Would need the brells line in there.  Also in spell rotation there is only Force of Piety.  I would like to see Ancient: Force of Chaos and Serene Command in there.  This seems odd because in Want Spells there is:  
![image](https://github.com/user-attachments/assets/6c4468cc-0d6e-4abe-a241-a3880d1965df)

I also noticed that cleric isn't offering any standard buffs (ageo or symbol) buffs even though they are checked in offer and Serve Buff Requests are on.  Same goes with druid hp buff, shaman focus buff.  

Am I not understanding how the buffing and requests are taken care of?  I assumed they would check toons to see if buffs are up to date.

On a side note the Short Term Buffs are being kept on toons.

**Comment by aquietone** [comment]
The buff begging depends on a few things:
- the class which offers the spell needs to have the spell in the spell line. in the case of pally i never populated all the brells spell names so it didn't find one to offer.
- the spell line needs to meet whatever condition it might need for casting the spell. in the case of cleric aego, i had a condition for less than lvl 70 as i had a buff stick on lazarus and just wanted my cleric to stop wasting time casting conviction. (same with dru/shm)
- buff stack checks are performed on the receiving toon that asks for the buff.
- buffers need to have the buff checked in skills>buffs>offer buffs
- buffees need to have the buff checked in skills>buffs>want buffs

on the debug tab > state inspector, you can expand `actors` and see what toons are broadcasting in terms of buffs they are offering / wanting.

will update things in a bit to:
1. define all the brells spell line
2. remove the < lvl 70 condition on cleric aego, dru skin, shm focus
3. add DS alias to druid DS line

On the paladin spell choices:
Paladin is the class i've played the least (never on live, only very recently on emu). I've mostly no idea how to play one well yet.
I've updated the spells a bit so see if the lineup seems better now.

**Comment by Kausaliax** [comment]
Ok.  Noticed one thing.  

So I was having an issue with shaman not casting Lingering Sloth (slowproc) and figured out why.  I had shaman using BYOS.  Even though Lingering sloth was loaded in it's spellbar it refused to cast it.

**Comment by Kausaliax** [comment]
On another buff note for Shaman is the Spirit of the Panther.   Utility Beneficial > Combat Innates > Spirit of the Panther to find the spell.  This is an offensive damage proc but can only be cast on a group member.  Is this able to be put in the shaman list or no?

**Comment by Kausaliax** [comment]
Let me know when you have the updates done:   

define all the brells spell line
remove the < lvl 70 condition on cleric aego, dru skin, shm focus
add DS alias to druid DS line

Thanks so much for your hard work )

**Comment by aquietone** [comment]
Those ones mentioned should be there since yesterday, at least my buffers started casting those buffs now if i turned them on.

Will take a look at the shm stuff eventually.

**Comment by aquietone** [comment]
Looks like on laz we have a clicky with talisman of the panther so never looked much at the spirit of the panther spell line.
Added MELEEPROC under the buff beg which should enable begging for spirit of the panther spell line (or talisman instead if the shaman has that)
For lingering sloth, make sure you have the option enabled to cast it, I'm not sure why it wouldn't work with BYOS on otherwise.

**Comment by Kausaliax** [comment]
Thanks, will reload and test it out.

I have one observation:  I run 18 toons on one pc and 18 on another pc.  They are all connected on eqbc and dannet.  My shaman on one pc will not buff my shadow knight on the laptop who is running AQO lua.  Is there any way to accomplish this?

**Comment by aquietone** [comment]
the buff begging is based on mq actor system which is local only. if/when actors support networking, buff begging will support across PCs. til then i don't have any plans to work around it.

**Comment by Kausaliax** [comment]
Ok thanks.

Druid casts HP buff, Cleric casts Symbol and Ageo.  Chanter casts haste and kei just fine.

Only Damage Shield druid will buff is a low level one.  The lvl 70 DS is Legacy of Nettles.
Shaman will now only cast Champion.  Will not cast slow proc, melee proc or focus on anyone.
Paladin will not cast Brells Stalwart Shield on anyone.
