### ISSUE TITLE
Missing buffs in Want Buffs and Offer Buffs

### ISSUE THREAD

**Issue by Kausaliax** [aquietone/aqobot#32]
Druid:  Blessing of Oak (Group regen), Flight of Eagles, Pack Shrew (indoor movement speed)
Shaman: Talisman of Perseverance (Group regen), Pack Shrew (indoor movement speed)
Enchanter:  Guard of Druzzil (Group GMR)
Cleric:  Aura of Devotion (Spell Haste)

As I come across more I will post here if you want.

**Comment by aquietone** [comment]
All added
