### ISSUE TITLE
Beastlord issue

### ISSUE THREAD

**Issue by Kausaliax** [aquietone/aqobot#33]
My beastlord is in a loop memming Glacier Spear in gem slot 1, then 4, rinse repeat.

**Comment by aquietone** [comment]
Should be fixed, it tries to mem some frost nuke line in gem1 (was maelstrom nukes on live) and lance nuke lines in 4,5.
So ancient: savage ice in 1 and glacier spear in 4 on project lazarus at least.

**Comment by Kausaliax** [comment]
That addressed the issue, but another popped up.  My beastlord now tries to sit unsuccessfully and loops trying to sit.  Stops this behavior only if i open the spellbook.  No other macros running, just aqo lua.
