### ISSUE TITLE
Mag Custom Pull Range Slightly Too High

### ISSUE THREAD

**Issue by towbes** [aquietone/aqobot#9]
Mag pull routine can get stuck sometimes because it stops moving ~200 distance from mob, but pet attack doesn't always work from that distance. Might be more stable to go to 150-175 distance for the /pet attack command to avoid the jerky movements when mobs are moving

**Comment by towbes** [comment]
Part of the reason is the pet needs to be in a certain distance so usually is lagging behind the mag a bit

**Comment by towbes** [comment]
Adding a distance check before the movement stop seems to have helped, but not sure if that's the ideal approach

```
function Magician:pullCustom()
    if mq.TLO.Target.Distance3D() < 175 then
        movement.stop()
    end
    mq.cmd('/pet attack')
    mq.cmd('/pet swarm')
    mq.delay(1000)
end
```

**Comment by aquietone** [comment]
added distance check, same to shd which had similar for its pull spell
